cp /scratch/jl11523/projects/Qwen-VL/BUILD.md .
cp /scratch/jl11523/projects/Qwen-VL/Dockerfile.qwendemo .
cp /scratch/jl11523/projects/Qwen-VL/Dockerfile.qwenint4openai .
cp /scratch/jl11523/projects/Qwen-VL/Dockerfile.qwenopenai .
cp /scratch/jl11523/projects/Qwen-VL/FAQ_ja.md .
cp /scratch/jl11523/projects/Qwen-VL/FAQ_ko.md .
cp /scratch/jl11523/projects/Qwen-VL/FAQ_zh.md .
cp /scratch/jl11523/projects/Qwen-VL/FAQ.md .
cp /scratch/jl11523/projects/Qwen-VL/LICENSE .
cp /scratch/jl11523/projects/Qwen-VL/NOTICE .
cp /scratch/jl11523/projects/Qwen-VL/openai_api.py .
cp /scratch/jl11523/projects/Qwen-VL/README_CN.md .
cp /scratch/jl11523/projects/Qwen-VL/README_JA.md .
cp /scratch/jl11523/projects/Qwen-VL/README_KO.md .
cp /scratch/jl11523/projects/Qwen-VL/README.md .
cp /scratch/jl11523/projects/Qwen-VL/requirements_openai_api.txt .
cp /scratch/jl11523/projects/Qwen-VL/requirements_web_demo.txt .
cp /scratch/jl11523/projects/Qwen-VL/requirements.txt .
cp /scratch/jl11523/projects/Qwen-VL/TUTORIAL_ja.md .
cp /scratch/jl11523/projects/Qwen-VL/TUTORIAL_ko.md .
cp /scratch/jl11523/projects/Qwen-VL/TUTORIAL_zh.md .
cp /scratch/jl11523/projects/Qwen-VL/TUTORIAL.md .
cp /scratch/jl11523/projects/Qwen-VL/web_demo_mm.py .